### ISSUE TITLE
[CHORE]: Workflow 구현하기 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#1]
### 작업 사항

Workflows 구현 
- Create Issues Workflow
- 이슈 생성시 디스코드 메세지
- 이슈 생성시 지라 이슈 함께 생성 

PR, Issue -> Discord 메세지 전달

CI -> 빌드, 린트, 테스트 작업 

### Todo

- [x] Discord Web Hook 탐색 및 secret 설정 
- [x] Github Action을 통해 Issue workflow 구현 (with discord) 
- [x] Jira Web Hook 탐색 및 secret 설정 
- [x] Github Action을 통해 Issue workflow 구현 (with jira) 
- [x] Github Action을 통해 PR workflow 구현 -> 빌드 성공, 실패에 따라 디스코드로 알림,
