### ISSUE TITLE
[FEATURE]: 피그마 메인 그리고 설정 페이지 UI/UX 구현

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#10]
### 작업 사항

Figma 메인 페이지 구현 

=
- 

### Todo

- [x] 운영진 페이지 화면 UI/UX 구현 
- [x] 공지사항 페이지  화면 UI/UX 구현 
- [x] 설문조사 페이지   화면 UI/UX 구현 

### 기타사항

아좌아좌 !
