### ISSUE TITLE
[FIX]: 설문응답 이전 버튼 클릭시, 응답 검증 및 상태 저장 버그 수정 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#128]
### 작업 사항

#94 설문작성시 설문 형식 정보 소개 UI 구현 이슈에서 추가된 기능 중 

이전 버튼 클릭시 응답 저장 기능이 추가됨. 

하지만, 다음 버튼을 통해 저장된 응답과 다르게, 

1. 형식 Validation을 검증하지 않고 
2. 작성된 응답을 재 수정하는 경우, 수정된 응답이 저장되는 로직이 빠져있었음. 

### Todo

- [x] 이전 버튼 클릭시 형식 검증 로직 수행
- [x] 기존 응답을 수정한 경우, 응답 목록 데이터 수정 로직 추가 
- [x] 상단 TopBar Horizontal Padding 맞지 않는 부분 수정
