### ISSUE TITLE
[FEATURE]: Firebase - Github 로그인 로직 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#14]
### 작업 사항

FirebaseAuth 연동으로 Github 로그인 로직 구현 

### Todo

- [x] FirebaseAuth - Github Token 프로젝트 설정  
- [x] SignIn Response & Domain Model 구현  
- [x] Github 로그인 구현 로직 및 유스케이스 구현 

### 기타사항

첫 기능 구현 시작!

**Comment by jeongjaino** [comment]
<img width="1270" alt="image" src="https://github.com/pknu-wap/WAPP/assets/77484719/32fe8d6d-7aaa-4c8e-ad3d-520cab9df3d5">
