### ISSUE TITLE
[FEATURE]: 설문 관리 페이지 UI 개선 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#140]
### 작업 사항

설문 관리 페이지 UI 개선

dummy data 걷어내고 실 행사 데이터 삽입하기 

설문 관리 페이지 피그마 만들기 및 UI 개선하기 

### Todo

- [x] 더미데이터에서 실 행사 데이터로 변경
- [x] 설문 관리 페이지 피그마 구현
- [x] 설문 관리 페이지 UI 개선하기
