### ISSUE TITLE
[FEATURE] : 회원가입 로직 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#15]
### 작업 사항

회원가입 로직 구현 

### Todo

- [x] 로그인시 등록되지 않는 회원인 경우 회원가입으로 전환
- [x] 회원가입 Domain Model 구현 
- [x] Firestore 데이터 저장
