### ISSUE TITLE
[FEATURE]: 회원가입/로그인 화면 및 로직 결합 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#17]
### 작업 사항

회원가입/로그인 화면 및 로직 결합 
그리고 예외처리

### Todo

- [x] 로그인 화면과 로직 결합
- [x] 회원가입 화면과 로직 결합 
- [x] 예외 및 실패 처리
