### ISSUE TITLE
[FEATURE]: 안드로이드 프로젝트 생성 및 초기 세팅

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#2]
### 작업 사항

다른 작업을 하기 위한 안드로이드 프로젝트 생성 및 초기 세팅 수행

### Todo

- [x] 안드로이드 프로젝트 생성
- [x] core / feature 모듈 생성
- [x] Version Catalog, Custom Plugin 파일 및 모듈 생성
