### ISSUE TITLE
[FEATURE]: 운영진 인증 시스템 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#32]
### 작업 사항

Firestore를 활용한 운영진 인증 로직 구현 

### Todo

- [x] Firestore code, managers 테이블 구현
- [x] 등록된 운영진 중, 현재 userId 조회 로직 구현
- [x] 운영진 코드 검증 로직 구현 

### 기타사항
운영 페이지 입장 -> 운영진 테이블에 현재 사용자 조회 -> 없는 경우 운영진 코드 작성 로직 
운영 페이지 입장 -> 인가 -> 인증 

_No response_
