### ISSUE TITLE
[FEATURE]: common 모듈 구현 및 예외 처리 로직 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#35]
### 작업 사항

1. 네트워크 연결과 같은 비즈니스 로직 수행중 발생하는 예외에 관한 알림 로직 구현 
2. base Modue -> common Module 변경, common/base, common/extensions, commoon/etc

### Todo

- [x] 예외 처리 로직 구현
- [x] 예외에 따른 SnackBar Component Composable 구현 
- [x] common Module에 utils migration
