### ISSUE TITLE
[FEATURE]: 운영진 인증 디알로그 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#38]
### 작업 사항

운영진 인증 디알로그 구현 및 로직 결합 

### Todo

- [x] 운영진 인증 디알로그 UI 구현
- [x] 도메인 로직과 결합
- [x] 다른 화면과 전환 설정

**Comment by jeongjaino** [comment]
validation vs verification 

status vs state 차이 ㄷㄷㄷㅎㄷㅎㄷㄷㅎㄷㅎㄷㅎㄷㅎ

**Comment by jeongjaino** [comment]
변하는 경우 State, 더 이상 변하지 않거나 거의 변하지 않는 경우 status,

validation -> 결과의 확인 
verification -> 과정의 확인
