### ISSUE TITLE
[CHORE]: manage -> management renaming 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#40]
### 작업 사항

클래스, 모듈 등등 manage -> management로 이름 수정 

### Todo

- [x] 모듈 네이밍 수정
- [x] 클래스 네이밍 수정
- [x] management 관련 함수 네이밍 수정
