### ISSUE TITLE
[FEATURE]: (관리페이지) 설문조사 불러오기 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#42]
### 작업 사항

관리 페이지에 들어갈 

작성된 설문조사 불러오는 로직 구현 및 UI 구현 

### Todo

- [x] 공지사항 불러오는 로직 및 유스케이스 구현 
- [x] 공지사항 컴포넌트 구현 
- [x] 로직과 유아이 결합

**Comment by jeongjaino** [comment]
<img width="458" alt="image" src="https://github.com/pknu-wap/WAPP/assets/77484719/ad745d4f-aa11-4a49-ae59-46eecbbc25dc">
