### ISSUE TITLE
[CHORE]: Firebase 세팅 및 구축

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#6]
### 작업 사항

Firebase 사용하기 위해 프로젝트 생성 및 종속성 추가하기 

### Todo

- [x] Firebase Project (Auth, firestore, Crashlytics, Analytics) 프로젝트 생성
- [x] google.service json 프로젝트 추가 및 Github secrets 등록하기 
- [x] Version Catalog에 종속성 추가 
- [x] Google Service Custom Convention Plugin

### 기타사항

이번에는 진짜로 Firebase Analytics Event 직접 찍어봅시다!
