### ISSUE TITLE
[CHORE]: 엔티티 설계 및 행사 데이터 베이스 구축

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#9]
### 작업 사항

WAPP 엔티티 설계 및 행사 정보 데이터 확보 및 구축 

### Todo

- [x] 어플리케이션 엔티티 설계 
- [x] ERD 다이어그램 구현 
- [x] 행사 정보 데이터 확보 
- [x] Firestore 행사 테이블 구현 

### 기타사항

인생 첫 ERD 체험기 두두등장

**Comment by jeongjaino** [comment]
<img width="1358" alt="image" src="https://github.com/pknu-wap/WAPP/assets/77484719/ab81fc45-3902-4b43-b520-261b80ef9177">

**Comment by jeongjaino** [comment]
![image](https://github.com/pknu-wap/WAPP/assets/77484719/a9f21f09-05fd-4f82-8988-ffba3a01c0df)
