### ISSUE TITLE
[FEATURE]: 설문 등록 및 작성 시, 이전 정보 수정 기능 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/WAPP#95]
### 작업 사항

설문 등록 및 작성 시 

한번 등록하고 다음 페이지로 넘어가면, 이전 페이지로 돌아갈 수 없음. 

이전 페이지로 돌아가, 이전 정보를 수정하는 기능 구현 

### Todo

- [x] 피그마 UI 수정
- [x] 뒤로 가는 로직 구현 
- [x] 이전 정보 수정 기능 구현
